// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GseGrpcSdkService.proto

package grpcsdk

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 游戏进程ProcessReady 调用
type ProcessReadyRequest struct {
	LogPathsToUpload     []string `protobuf:"bytes,1,rep,name=logPathsToUpload,proto3" json:"logPathsToUpload,omitempty"`
	ClientPort           int32    `protobuf:"varint,2,opt,name=clientPort,proto3" json:"clientPort,omitempty"`
	GrpcPort             int32    `protobuf:"varint,3,opt,name=grpcPort,proto3" json:"grpcPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessReadyRequest) Reset()         { *m = ProcessReadyRequest{} }
func (m *ProcessReadyRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessReadyRequest) ProtoMessage()    {}
func (*ProcessReadyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{0}
}

func (m *ProcessReadyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessReadyRequest.Unmarshal(m, b)
}
func (m *ProcessReadyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessReadyRequest.Marshal(b, m, deterministic)
}
func (m *ProcessReadyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessReadyRequest.Merge(m, src)
}
func (m *ProcessReadyRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessReadyRequest.Size(m)
}
func (m *ProcessReadyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessReadyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessReadyRequest proto.InternalMessageInfo

func (m *ProcessReadyRequest) GetLogPathsToUpload() []string {
	if m != nil {
		return m.LogPathsToUpload
	}
	return nil
}

func (m *ProcessReadyRequest) GetClientPort() int32 {
	if m != nil {
		return m.ClientPort
	}
	return 0
}

func (m *ProcessReadyRequest) GetGrpcPort() int32 {
	if m != nil {
		return m.GrpcPort
	}
	return 0
}

// 游戏进程在收到GSE的启动游戏会话后需要调用
type ActivateGameServerSessionRequest struct {
	GameServerSessionId  string   `protobuf:"bytes,1,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	MaxPlayers           int32    `protobuf:"varint,2,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateGameServerSessionRequest) Reset()         { *m = ActivateGameServerSessionRequest{} }
func (m *ActivateGameServerSessionRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateGameServerSessionRequest) ProtoMessage()    {}
func (*ActivateGameServerSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{1}
}

func (m *ActivateGameServerSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateGameServerSessionRequest.Unmarshal(m, b)
}
func (m *ActivateGameServerSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateGameServerSessionRequest.Marshal(b, m, deterministic)
}
func (m *ActivateGameServerSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateGameServerSessionRequest.Merge(m, src)
}
func (m *ActivateGameServerSessionRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateGameServerSessionRequest.Size(m)
}
func (m *ActivateGameServerSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateGameServerSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateGameServerSessionRequest proto.InternalMessageInfo

func (m *ActivateGameServerSessionRequest) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

func (m *ActivateGameServerSessionRequest) GetMaxPlayers() int32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

// 游戏进程在玩家加入后调用
type AcceptPlayerSessionRequest struct {
	GameServerSessionId  string   `protobuf:"bytes,1,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	PlayerSessionId      string   `protobuf:"bytes,2,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptPlayerSessionRequest) Reset()         { *m = AcceptPlayerSessionRequest{} }
func (m *AcceptPlayerSessionRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptPlayerSessionRequest) ProtoMessage()    {}
func (*AcceptPlayerSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{2}
}

func (m *AcceptPlayerSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptPlayerSessionRequest.Unmarshal(m, b)
}
func (m *AcceptPlayerSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptPlayerSessionRequest.Marshal(b, m, deterministic)
}
func (m *AcceptPlayerSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptPlayerSessionRequest.Merge(m, src)
}
func (m *AcceptPlayerSessionRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptPlayerSessionRequest.Size(m)
}
func (m *AcceptPlayerSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptPlayerSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptPlayerSessionRequest proto.InternalMessageInfo

func (m *AcceptPlayerSessionRequest) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

func (m *AcceptPlayerSessionRequest) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

// 游戏进程在玩家移除后调用
type RemovePlayerSessionRequest struct {
	GameServerSessionId  string   `protobuf:"bytes,1,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	PlayerSessionId      string   `protobuf:"bytes,2,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePlayerSessionRequest) Reset()         { *m = RemovePlayerSessionRequest{} }
func (m *RemovePlayerSessionRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePlayerSessionRequest) ProtoMessage()    {}
func (*RemovePlayerSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{3}
}

func (m *RemovePlayerSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePlayerSessionRequest.Unmarshal(m, b)
}
func (m *RemovePlayerSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePlayerSessionRequest.Marshal(b, m, deterministic)
}
func (m *RemovePlayerSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePlayerSessionRequest.Merge(m, src)
}
func (m *RemovePlayerSessionRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePlayerSessionRequest.Size(m)
}
func (m *RemovePlayerSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePlayerSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePlayerSessionRequest proto.InternalMessageInfo

func (m *RemovePlayerSessionRequest) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

func (m *RemovePlayerSessionRequest) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

// 玩家信息
type PlayerSession struct {
	PlayerSessionId      string   `protobuf:"bytes,1,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	PlayerId             string   `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	GameServerSessionId  string   `protobuf:"bytes,3,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	FleetId              string   `protobuf:"bytes,4,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	IpAddress            string   `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreationTime         int64    `protobuf:"varint,7,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	TerminationTime      int64    `protobuf:"varint,8,opt,name=terminationTime,proto3" json:"terminationTime,omitempty"`
	Port                 int32    `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	PlayerData           string   `protobuf:"bytes,10,opt,name=playerData,proto3" json:"playerData,omitempty"`
	DnsName              string   `protobuf:"bytes,11,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSession) Reset()         { *m = PlayerSession{} }
func (m *PlayerSession) String() string { return proto.CompactTextString(m) }
func (*PlayerSession) ProtoMessage()    {}
func (*PlayerSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{4}
}

func (m *PlayerSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSession.Unmarshal(m, b)
}
func (m *PlayerSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSession.Marshal(b, m, deterministic)
}
func (m *PlayerSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSession.Merge(m, src)
}
func (m *PlayerSession) XXX_Size() int {
	return xxx_messageInfo_PlayerSession.Size(m)
}
func (m *PlayerSession) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSession.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSession proto.InternalMessageInfo

func (m *PlayerSession) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

func (m *PlayerSession) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *PlayerSession) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

func (m *PlayerSession) GetFleetId() string {
	if m != nil {
		return m.FleetId
	}
	return ""
}

func (m *PlayerSession) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *PlayerSession) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PlayerSession) GetCreationTime() int64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *PlayerSession) GetTerminationTime() int64 {
	if m != nil {
		return m.TerminationTime
	}
	return 0
}

func (m *PlayerSession) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PlayerSession) GetPlayerData() string {
	if m != nil {
		return m.PlayerData
	}
	return ""
}

func (m *PlayerSession) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

// 游戏进程获取玩家信息
type DescribePlayerSessionsRequest struct {
	GameServerSessionId       string   `protobuf:"bytes,1,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	PlayerId                  string   `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerSessionId           string   `protobuf:"bytes,3,opt,name=playerSessionId,proto3" json:"playerSessionId,omitempty"`
	PlayerSessionStatusFilter string   `protobuf:"bytes,4,opt,name=playerSessionStatusFilter,proto3" json:"playerSessionStatusFilter,omitempty"`
	NextToken                 string   `protobuf:"bytes,5,opt,name=nextToken,proto3" json:"nextToken,omitempty"`
	Limit                     int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *DescribePlayerSessionsRequest) Reset()         { *m = DescribePlayerSessionsRequest{} }
func (m *DescribePlayerSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribePlayerSessionsRequest) ProtoMessage()    {}
func (*DescribePlayerSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{5}
}

func (m *DescribePlayerSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePlayerSessionsRequest.Unmarshal(m, b)
}
func (m *DescribePlayerSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePlayerSessionsRequest.Marshal(b, m, deterministic)
}
func (m *DescribePlayerSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePlayerSessionsRequest.Merge(m, src)
}
func (m *DescribePlayerSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribePlayerSessionsRequest.Size(m)
}
func (m *DescribePlayerSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePlayerSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePlayerSessionsRequest proto.InternalMessageInfo

func (m *DescribePlayerSessionsRequest) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetPlayerSessionId() string {
	if m != nil {
		return m.PlayerSessionId
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetPlayerSessionStatusFilter() string {
	if m != nil {
		return m.PlayerSessionStatusFilter
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *DescribePlayerSessionsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DescribePlayerSessionsResponse struct {
	NextToken            string           `protobuf:"bytes,1,opt,name=nextToken,proto3" json:"nextToken,omitempty"`
	PlayerSessions       []*PlayerSession `protobuf:"bytes,2,rep,name=playerSessions,proto3" json:"playerSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DescribePlayerSessionsResponse) Reset()         { *m = DescribePlayerSessionsResponse{} }
func (m *DescribePlayerSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribePlayerSessionsResponse) ProtoMessage()    {}
func (*DescribePlayerSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{6}
}

func (m *DescribePlayerSessionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribePlayerSessionsResponse.Unmarshal(m, b)
}
func (m *DescribePlayerSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribePlayerSessionsResponse.Marshal(b, m, deterministic)
}
func (m *DescribePlayerSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribePlayerSessionsResponse.Merge(m, src)
}
func (m *DescribePlayerSessionsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribePlayerSessionsResponse.Size(m)
}
func (m *DescribePlayerSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribePlayerSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribePlayerSessionsResponse proto.InternalMessageInfo

func (m *DescribePlayerSessionsResponse) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *DescribePlayerSessionsResponse) GetPlayerSessions() []*PlayerSession {
	if m != nil {
		return m.PlayerSessions
	}
	return nil
}

// 游戏进程更新玩家加入策略
type UpdatePlayerSessionCreationPolicyRequest struct {
	GameServerSessionId            string   `protobuf:"bytes,1,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	NewPlayerSessionCreationPolicy string   `protobuf:"bytes,2,opt,name=newPlayerSessionCreationPolicy,proto3" json:"newPlayerSessionCreationPolicy,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *UpdatePlayerSessionCreationPolicyRequest) Reset() {
	*m = UpdatePlayerSessionCreationPolicyRequest{}
}
func (m *UpdatePlayerSessionCreationPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerSessionCreationPolicyRequest) ProtoMessage()    {}
func (*UpdatePlayerSessionCreationPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{7}
}

func (m *UpdatePlayerSessionCreationPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerSessionCreationPolicyRequest.Unmarshal(m, b)
}
func (m *UpdatePlayerSessionCreationPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerSessionCreationPolicyRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerSessionCreationPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerSessionCreationPolicyRequest.Merge(m, src)
}
func (m *UpdatePlayerSessionCreationPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerSessionCreationPolicyRequest.Size(m)
}
func (m *UpdatePlayerSessionCreationPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerSessionCreationPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerSessionCreationPolicyRequest proto.InternalMessageInfo

func (m *UpdatePlayerSessionCreationPolicyRequest) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

func (m *UpdatePlayerSessionCreationPolicyRequest) GetNewPlayerSessionCreationPolicy() string {
	if m != nil {
		return m.NewPlayerSessionCreationPolicy
	}
	return ""
}

// 游戏进程在结束游戏会话后调用
type TerminateGameServerSessionRequest struct {
	GameServerSessionId  string   `protobuf:"bytes,1,opt,name=gameServerSessionId,proto3" json:"gameServerSessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateGameServerSessionRequest) Reset()         { *m = TerminateGameServerSessionRequest{} }
func (m *TerminateGameServerSessionRequest) String() string { return proto.CompactTextString(m) }
func (*TerminateGameServerSessionRequest) ProtoMessage()    {}
func (*TerminateGameServerSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{8}
}

func (m *TerminateGameServerSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateGameServerSessionRequest.Unmarshal(m, b)
}
func (m *TerminateGameServerSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateGameServerSessionRequest.Marshal(b, m, deterministic)
}
func (m *TerminateGameServerSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateGameServerSessionRequest.Merge(m, src)
}
func (m *TerminateGameServerSessionRequest) XXX_Size() int {
	return xxx_messageInfo_TerminateGameServerSessionRequest.Size(m)
}
func (m *TerminateGameServerSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateGameServerSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateGameServerSessionRequest proto.InternalMessageInfo

func (m *TerminateGameServerSessionRequest) GetGameServerSessionId() string {
	if m != nil {
		return m.GameServerSessionId
	}
	return ""
}

// 游戏进程在退出时调用
type ProcessEndingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessEndingRequest) Reset()         { *m = ProcessEndingRequest{} }
func (m *ProcessEndingRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessEndingRequest) ProtoMessage()    {}
func (*ProcessEndingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{9}
}

func (m *ProcessEndingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessEndingRequest.Unmarshal(m, b)
}
func (m *ProcessEndingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessEndingRequest.Marshal(b, m, deterministic)
}
func (m *ProcessEndingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessEndingRequest.Merge(m, src)
}
func (m *ProcessEndingRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessEndingRequest.Size(m)
}
func (m *ProcessEndingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessEndingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessEndingRequest proto.InternalMessageInfo

// 上报自定义数据
type ReportCustomDataRequest struct {
	CurrentCustomCount   int32    `protobuf:"varint,1,opt,name=currentCustomCount,proto3" json:"currentCustomCount,omitempty"`
	MaxCustomCount       int32    `protobuf:"varint,2,opt,name=maxCustomCount,proto3" json:"maxCustomCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportCustomDataRequest) Reset()         { *m = ReportCustomDataRequest{} }
func (m *ReportCustomDataRequest) String() string { return proto.CompactTextString(m) }
func (*ReportCustomDataRequest) ProtoMessage()    {}
func (*ReportCustomDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{10}
}

func (m *ReportCustomDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportCustomDataRequest.Unmarshal(m, b)
}
func (m *ReportCustomDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportCustomDataRequest.Marshal(b, m, deterministic)
}
func (m *ReportCustomDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCustomDataRequest.Merge(m, src)
}
func (m *ReportCustomDataRequest) XXX_Size() int {
	return xxx_messageInfo_ReportCustomDataRequest.Size(m)
}
func (m *ReportCustomDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCustomDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCustomDataRequest proto.InternalMessageInfo

func (m *ReportCustomDataRequest) GetCurrentCustomCount() int32 {
	if m != nil {
		return m.CurrentCustomCount
	}
	return 0
}

func (m *ReportCustomDataRequest) GetMaxCustomCount() int32 {
	if m != nil {
		return m.MaxCustomCount
	}
	return 0
}

// 返回结果，成功与否看rpc错误码
type GseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GseResponse) Reset()         { *m = GseResponse{} }
func (m *GseResponse) String() string { return proto.CompactTextString(m) }
func (*GseResponse) ProtoMessage()    {}
func (*GseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eab5f358ca1d055, []int{11}
}

func (m *GseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GseResponse.Unmarshal(m, b)
}
func (m *GseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GseResponse.Marshal(b, m, deterministic)
}
func (m *GseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GseResponse.Merge(m, src)
}
func (m *GseResponse) XXX_Size() int {
	return xxx_messageInfo_GseResponse.Size(m)
}
func (m *GseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProcessReadyRequest)(nil), "tencentcloud.gse.grpcsdk.ProcessReadyRequest")
	proto.RegisterType((*ActivateGameServerSessionRequest)(nil), "tencentcloud.gse.grpcsdk.ActivateGameServerSessionRequest")
	proto.RegisterType((*AcceptPlayerSessionRequest)(nil), "tencentcloud.gse.grpcsdk.AcceptPlayerSessionRequest")
	proto.RegisterType((*RemovePlayerSessionRequest)(nil), "tencentcloud.gse.grpcsdk.RemovePlayerSessionRequest")
	proto.RegisterType((*PlayerSession)(nil), "tencentcloud.gse.grpcsdk.PlayerSession")
	proto.RegisterType((*DescribePlayerSessionsRequest)(nil), "tencentcloud.gse.grpcsdk.DescribePlayerSessionsRequest")
	proto.RegisterType((*DescribePlayerSessionsResponse)(nil), "tencentcloud.gse.grpcsdk.DescribePlayerSessionsResponse")
	proto.RegisterType((*UpdatePlayerSessionCreationPolicyRequest)(nil), "tencentcloud.gse.grpcsdk.UpdatePlayerSessionCreationPolicyRequest")
	proto.RegisterType((*TerminateGameServerSessionRequest)(nil), "tencentcloud.gse.grpcsdk.TerminateGameServerSessionRequest")
	proto.RegisterType((*ProcessEndingRequest)(nil), "tencentcloud.gse.grpcsdk.ProcessEndingRequest")
	proto.RegisterType((*ReportCustomDataRequest)(nil), "tencentcloud.gse.grpcsdk.ReportCustomDataRequest")
	proto.RegisterType((*GseResponse)(nil), "tencentcloud.gse.grpcsdk.GseResponse")
}

func init() { proto.RegisterFile("GseGrpcSdkService.proto", fileDescriptor_3eab5f358ca1d055) }

var fileDescriptor_3eab5f358ca1d055 = []byte{
	// 781 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x7e, 0xdd, 0x34, 0x6d, 0x33, 0xfd, 0xde, 0x56, 0xad, 0x1b, 0xbd, 0x6f, 0x95, 0x5a, 0x7a,
	0x21, 0x42, 0x6a, 0x80, 0x82, 0x04, 0x02, 0x2e, 0xfd, 0xa0, 0x51, 0x2f, 0x10, 0x39, 0xe9, 0x85,
	0x9b, 0x6b, 0x4f, 0x53, 0xab, 0xf6, 0xae, 0xbb, 0xbb, 0x29, 0xe9, 0x01, 0x09, 0x71, 0xe3, 0x80,
	0xe0, 0x47, 0xf0, 0xf3, 0xb8, 0xf1, 0x07, 0x90, 0x37, 0x4e, 0x1a, 0xa7, 0xde, 0x24, 0x2d, 0x88,
	0x5b, 0xf6, 0x99, 0xf1, 0x3c, 0xb3, 0x7e, 0xc6, 0xcf, 0x04, 0xd6, 0xab, 0x02, 0xab, 0x3c, 0x72,
	0xeb, 0xde, 0x79, 0x1d, 0xf9, 0xa5, 0xef, 0x62, 0x25, 0xe2, 0x4c, 0x32, 0x62, 0x4a, 0xa4, 0x2e,
	0x52, 0xe9, 0x06, 0xac, 0xe5, 0x55, 0x9a, 0x02, 0x2b, 0x4d, 0x1e, 0xb9, 0xc2, 0x3b, 0xb7, 0x3e,
	0xc0, 0x4a, 0x8d, 0x33, 0x17, 0x85, 0xb0, 0xd1, 0xf1, 0xae, 0x6c, 0xbc, 0x68, 0xa1, 0x90, 0xe4,
	0x01, 0x2c, 0x05, 0xac, 0x59, 0x73, 0xe4, 0x99, 0x68, 0xb0, 0xe3, 0x28, 0x60, 0x8e, 0x67, 0x1a,
	0xa5, 0x5c, 0xb9, 0x60, 0xdf, 0xc0, 0xc9, 0x26, 0x80, 0x1b, 0xf8, 0x48, 0x65, 0x8d, 0x71, 0x69,
	0x4e, 0x94, 0x8c, 0x72, 0xde, 0xee, 0x43, 0x48, 0x11, 0x66, 0x62, 0x36, 0x15, 0xcd, 0xa9, 0x68,
	0xef, 0x6c, 0x49, 0x28, 0xed, 0xba, 0xd2, 0xbf, 0x74, 0x24, 0x56, 0x9d, 0x10, 0xe3, 0xae, 0x91,
	0xd7, 0x51, 0x08, 0x9f, 0xd1, 0x6e, 0x2f, 0x8f, 0x60, 0xa5, 0x39, 0x18, 0x3b, 0x8a, 0xdb, 0x31,
	0xca, 0x05, 0x3b, 0x2b, 0x14, 0x77, 0x14, 0x3a, 0xed, 0x5a, 0xe0, 0x5c, 0x21, 0x17, 0xdd, 0x8e,
	0xae, 0x11, 0xab, 0x0d, 0xc5, 0x5d, 0xd7, 0xc5, 0x48, 0x76, 0x80, 0xdf, 0xe6, 0x2b, 0xc3, 0x62,
	0xd4, 0x5f, 0xe9, 0xc8, 0x53, 0xa4, 0x05, 0x7b, 0x10, 0x8e, 0x99, 0x6d, 0x0c, 0xd9, 0x25, 0xfe,
	0x75, 0xe6, 0x9f, 0x13, 0x30, 0x9f, 0x22, 0xcd, 0x7a, 0xd6, 0xc8, 0x7c, 0x36, 0x56, 0xb0, 0x03,
	0xf5, 0xca, 0xf7, 0xce, 0xba, 0x9e, 0x73, 0xfa, 0x9e, 0x4d, 0x98, 0x3e, 0x0d, 0x10, 0xe5, 0x91,
	0x67, 0x4e, 0xaa, 0xac, 0xee, 0x91, 0xfc, 0x0b, 0x05, 0x3f, 0xda, 0xf5, 0x3c, 0x8e, 0x42, 0x98,
	0x79, 0x15, 0xbb, 0x06, 0xc8, 0x1a, 0x4c, 0x09, 0xe9, 0xc8, 0x96, 0x30, 0xa7, 0x54, 0x28, 0x39,
	0x11, 0x0b, 0xe6, 0x5c, 0x8e, 0x8e, 0xf4, 0x19, 0x6d, 0xf8, 0x21, 0x9a, 0xd3, 0x25, 0xa3, 0x9c,
	0xb3, 0x53, 0x58, 0x7c, 0x57, 0x89, 0x3c, 0xf4, 0xe9, 0x75, 0xda, 0x8c, 0x4a, 0x1b, 0x84, 0x09,
	0x81, 0xc9, 0x28, 0x9e, 0xd4, 0x82, 0x9a, 0x1a, 0xf5, 0x3b, 0x9e, 0xa7, 0xce, 0x7d, 0x0f, 0x1c,
	0xe9, 0x98, 0xa0, 0xd8, 0xfb, 0x90, 0xf8, 0x46, 0x1e, 0x15, 0x6f, 0x9c, 0x10, 0xcd, 0xd9, 0xce,
	0x8d, 0x92, 0xa3, 0xf5, 0x79, 0x02, 0xfe, 0x3b, 0x40, 0xe1, 0x72, 0xff, 0x24, 0x2d, 0xb9, 0xb8,
	0xbb, 0xe6, 0xc3, 0xd4, 0xc8, 0xd0, 0x34, 0x97, 0xad, 0xe9, 0x2b, 0xd8, 0x48, 0x41, 0x75, 0xf5,
	0x32, 0x0f, 0xfd, 0x40, 0x22, 0x4f, 0x74, 0xd1, 0x27, 0xc4, 0x4a, 0x51, 0x6c, 0xcb, 0x06, 0x3b,
	0x47, 0xda, 0x55, 0xaa, 0x07, 0x90, 0x55, 0xc8, 0x07, 0x7e, 0xe8, 0x4b, 0x25, 0x54, 0xde, 0xee,
	0x1c, 0xac, 0xaf, 0x06, 0x6c, 0xea, 0xde, 0x85, 0x88, 0x18, 0x15, 0x98, 0x2e, 0x6b, 0x0c, 0x96,
	0x7d, 0x0b, 0x0b, 0xa9, 0x8e, 0xe2, 0x4f, 0x3b, 0x57, 0x9e, 0xdd, 0xb9, 0x5f, 0xd1, 0xd9, 0x5b,
	0x25, 0xfd, 0x99, 0x0d, 0x3c, 0x6e, 0x7d, 0x37, 0xa0, 0x7c, 0x1c, 0x79, 0x8e, 0x4c, 0xf7, 0xb3,
	0x9f, 0x4c, 0x4e, 0x8d, 0x05, 0xbe, 0x7b, 0x75, 0x77, 0xa1, 0x0e, 0x61, 0x93, 0xe2, 0xfb, 0x21,
	0xa5, 0x13, 0xf9, 0x46, 0x64, 0x59, 0xc7, 0xb0, 0xd5, 0x48, 0xa6, 0xf4, 0x0f, 0xba, 0xa4, 0xb5,
	0x06, 0xab, 0x89, 0xf5, 0xbf, 0xa6, 0x9e, 0x4f, 0x9b, 0x49, 0x25, 0xeb, 0x02, 0xd6, 0x6d, 0x8c,
	0xe7, 0x7e, 0xbf, 0x25, 0x24, 0x0b, 0xe3, 0x09, 0xef, 0x92, 0x54, 0x80, 0xb8, 0x2d, 0xce, 0x91,
	0x26, 0xb1, 0x7d, 0xd6, 0xa2, 0x52, 0x71, 0xe4, 0xed, 0x8c, 0x08, 0xb9, 0x07, 0x0b, 0xa1, 0xd3,
	0xee, 0xcf, 0xed, 0x98, 0xf1, 0x00, 0x6a, 0xcd, 0xc3, 0x6c, 0x55, 0x60, 0x77, 0x0c, 0x76, 0x7e,
	0xcc, 0xc0, 0xf2, 0x8d, 0x55, 0x46, 0x4e, 0x61, 0xae, 0x7f, 0x55, 0x91, 0xed, 0x21, 0xb2, 0xdf,
	0x5c, 0x69, 0xc5, 0xff, 0xf5, 0xe9, 0x7d, 0xdc, 0xd6, 0x3f, 0xe4, 0xa3, 0x01, 0x1b, 0xda, 0xa5,
	0x44, 0x5e, 0xe8, 0xcb, 0x8c, 0xda, 0x64, 0xe3, 0xb7, 0x20, 0x61, 0x25, 0x63, 0x41, 0x91, 0xa7,
	0xc3, 0xb8, 0x75, 0xfb, 0xec, 0x56, 0xac, 0x19, 0xcb, 0x69, 0x18, 0xab, 0x7e, 0x97, 0x8d, 0xcf,
	0xfa, 0xc5, 0x80, 0xb5, 0x6c, 0x5b, 0x20, 0xcf, 0xf4, 0x35, 0x86, 0x9a, 0x6a, 0xf1, 0xf9, 0xed,
	0x1f, 0xec, 0xf5, 0xf3, 0xcd, 0x80, 0xad, 0x91, 0xa6, 0x40, 0xf6, 0xf4, 0x0c, 0xe3, 0x3a, 0xca,
	0xf8, 0xaf, 0xe8, 0x93, 0x01, 0x45, 0xbd, 0x03, 0x90, 0x97, 0xfa, 0x3a, 0x23, 0x7d, 0x63, 0xfc,
	0x26, 0xce, 0x60, 0x3e, 0x65, 0x17, 0xa4, 0x32, 0xf2, 0xfb, 0x4b, 0xf9, 0xca, 0xf8, 0x4c, 0x14,
	0x96, 0x06, 0x0d, 0x88, 0x3c, 0x1e, 0x36, 0x84, 0x99, 0x66, 0x35, 0x36, 0xdf, 0xde, 0xf2, 0xbb,
	0xc5, 0x26, 0xdb, 0xf6, 0x30, 0x64, 0x0f, 0x93, 0x84, 0x93, 0x29, 0xf5, 0xbf, 0xf9, 0xc9, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x52, 0xfc, 0x30, 0x54, 0x52, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GseGrpcSdkServiceClient is the client API for GseGrpcSdkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GseGrpcSdkServiceClient interface {
	// 上报游戏进程已经就绪
	ProcessReady(ctx context.Context, in *ProcessReadyRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 激活游戏会话
	ActivateGameServerSession(ctx context.Context, in *ActivateGameServerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 玩家加入
	AcceptPlayerSession(ctx context.Context, in *AcceptPlayerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 玩家移除
	RemovePlayerSession(ctx context.Context, in *RemovePlayerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 获取玩家信息
	DescribePlayerSessions(ctx context.Context, in *DescribePlayerSessionsRequest, opts ...grpc.CallOption) (*DescribePlayerSessionsResponse, error)
	// 更新玩家加入策略
	UpdatePlayerSessionCreationPolicy(ctx context.Context, in *UpdatePlayerSessionCreationPolicyRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 结束游戏会话
	TerminateGameServerSession(ctx context.Context, in *TerminateGameServerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 结束进程
	ProcessEnding(ctx context.Context, in *ProcessEndingRequest, opts ...grpc.CallOption) (*GseResponse, error)
	// 上报自定义数据
	ReportCustomData(ctx context.Context, in *ReportCustomDataRequest, opts ...grpc.CallOption) (*GseResponse, error)
}

type gseGrpcSdkServiceClient struct {
	cc *grpc.ClientConn
}

func NewGseGrpcSdkServiceClient(cc *grpc.ClientConn) GseGrpcSdkServiceClient {
	return &gseGrpcSdkServiceClient{cc}
}

func (c *gseGrpcSdkServiceClient) ProcessReady(ctx context.Context, in *ProcessReadyRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ProcessReady", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) ActivateGameServerSession(ctx context.Context, in *ActivateGameServerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ActivateGameServerSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) AcceptPlayerSession(ctx context.Context, in *AcceptPlayerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/AcceptPlayerSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) RemovePlayerSession(ctx context.Context, in *RemovePlayerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/RemovePlayerSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) DescribePlayerSessions(ctx context.Context, in *DescribePlayerSessionsRequest, opts ...grpc.CallOption) (*DescribePlayerSessionsResponse, error) {
	out := new(DescribePlayerSessionsResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/DescribePlayerSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) UpdatePlayerSessionCreationPolicy(ctx context.Context, in *UpdatePlayerSessionCreationPolicyRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/UpdatePlayerSessionCreationPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) TerminateGameServerSession(ctx context.Context, in *TerminateGameServerSessionRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/TerminateGameServerSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) ProcessEnding(ctx context.Context, in *ProcessEndingRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ProcessEnding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gseGrpcSdkServiceClient) ReportCustomData(ctx context.Context, in *ReportCustomDataRequest, opts ...grpc.CallOption) (*GseResponse, error) {
	out := new(GseResponse)
	err := c.cc.Invoke(ctx, "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ReportCustomData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GseGrpcSdkServiceServer is the server API for GseGrpcSdkService service.
type GseGrpcSdkServiceServer interface {
	// 上报游戏进程已经就绪
	ProcessReady(context.Context, *ProcessReadyRequest) (*GseResponse, error)
	// 激活游戏会话
	ActivateGameServerSession(context.Context, *ActivateGameServerSessionRequest) (*GseResponse, error)
	// 玩家加入
	AcceptPlayerSession(context.Context, *AcceptPlayerSessionRequest) (*GseResponse, error)
	// 玩家移除
	RemovePlayerSession(context.Context, *RemovePlayerSessionRequest) (*GseResponse, error)
	// 获取玩家信息
	DescribePlayerSessions(context.Context, *DescribePlayerSessionsRequest) (*DescribePlayerSessionsResponse, error)
	// 更新玩家加入策略
	UpdatePlayerSessionCreationPolicy(context.Context, *UpdatePlayerSessionCreationPolicyRequest) (*GseResponse, error)
	// 结束游戏会话
	TerminateGameServerSession(context.Context, *TerminateGameServerSessionRequest) (*GseResponse, error)
	// 结束进程
	ProcessEnding(context.Context, *ProcessEndingRequest) (*GseResponse, error)
	// 上报自定义数据
	ReportCustomData(context.Context, *ReportCustomDataRequest) (*GseResponse, error)
}

func RegisterGseGrpcSdkServiceServer(s *grpc.Server, srv GseGrpcSdkServiceServer) {
	s.RegisterService(&_GseGrpcSdkService_serviceDesc, srv)
}

func _GseGrpcSdkService_ProcessReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).ProcessReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ProcessReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).ProcessReady(ctx, req.(*ProcessReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_ActivateGameServerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateGameServerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).ActivateGameServerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ActivateGameServerSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).ActivateGameServerSession(ctx, req.(*ActivateGameServerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_AcceptPlayerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptPlayerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).AcceptPlayerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/AcceptPlayerSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).AcceptPlayerSession(ctx, req.(*AcceptPlayerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_RemovePlayerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePlayerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).RemovePlayerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/RemovePlayerSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).RemovePlayerSession(ctx, req.(*RemovePlayerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_DescribePlayerSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePlayerSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).DescribePlayerSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/DescribePlayerSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).DescribePlayerSessions(ctx, req.(*DescribePlayerSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_UpdatePlayerSessionCreationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerSessionCreationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).UpdatePlayerSessionCreationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/UpdatePlayerSessionCreationPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).UpdatePlayerSessionCreationPolicy(ctx, req.(*UpdatePlayerSessionCreationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_TerminateGameServerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateGameServerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).TerminateGameServerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/TerminateGameServerSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).TerminateGameServerSession(ctx, req.(*TerminateGameServerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_ProcessEnding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessEndingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).ProcessEnding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ProcessEnding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).ProcessEnding(ctx, req.(*ProcessEndingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GseGrpcSdkService_ReportCustomData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCustomDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GseGrpcSdkServiceServer).ReportCustomData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tencentcloud.gse.grpcsdk.GseGrpcSdkService/ReportCustomData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GseGrpcSdkServiceServer).ReportCustomData(ctx, req.(*ReportCustomDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GseGrpcSdkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tencentcloud.gse.grpcsdk.GseGrpcSdkService",
	HandlerType: (*GseGrpcSdkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessReady",
			Handler:    _GseGrpcSdkService_ProcessReady_Handler,
		},
		{
			MethodName: "ActivateGameServerSession",
			Handler:    _GseGrpcSdkService_ActivateGameServerSession_Handler,
		},
		{
			MethodName: "AcceptPlayerSession",
			Handler:    _GseGrpcSdkService_AcceptPlayerSession_Handler,
		},
		{
			MethodName: "RemovePlayerSession",
			Handler:    _GseGrpcSdkService_RemovePlayerSession_Handler,
		},
		{
			MethodName: "DescribePlayerSessions",
			Handler:    _GseGrpcSdkService_DescribePlayerSessions_Handler,
		},
		{
			MethodName: "UpdatePlayerSessionCreationPolicy",
			Handler:    _GseGrpcSdkService_UpdatePlayerSessionCreationPolicy_Handler,
		},
		{
			MethodName: "TerminateGameServerSession",
			Handler:    _GseGrpcSdkService_TerminateGameServerSession_Handler,
		},
		{
			MethodName: "ProcessEnding",
			Handler:    _GseGrpcSdkService_ProcessEnding_Handler,
		},
		{
			MethodName: "ReportCustomData",
			Handler:    _GseGrpcSdkService_ReportCustomData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GseGrpcSdkService.proto",
}
